# Site settings
title: Akash Basudevan
email: akashbasudevan@gmail.com
url: https://zerocool95.github.io
description: "Optimistically Nihilistic and Artificially Intelligent"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/zerocool95
  - title: stack-overflow
    url: https://stackoverflow.com/users/6237573/akash-basudevan
  - title: github
    url: https://github.com/zerocool95
  - title: linkedin
    url: https://www.linkedin.com/in/akash-basudevan/
  - title: codechef
    url: https://www.codechef.com/users/zerocool95
  - title: codeforces
    url: http://codeforces.com/profile/ZerocooL95
  - title: hackerrank
    url: https://www.hackerrank.com/zerocool95
  - title: hackerearth
    url: https://www.hackerearth.com/@akashbasudevan
  - title: spoj
    url: https://www.spoj.com/users/zerocool95/

# Build settings
markdown: kramdown
permalink: pretty
